# Homework 4 - Python

First Name: Victory

Last Name: Okore

Group: 002

### After the assigment is done, please, push it to your [private GitHub repository](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/setting-repository-visibility) and invite [Majid-Sohrabi](https://github.com/Majid-Sohrabi)  as [collaborator](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository).

## Task 1 - Text to Emoji (1 point)

Write a Python program that takes input text containing emotions and converts them into corresponding emojis. Your program should replace specific text representations of emotions with appropriate emoji symbols. (Do mapping of all emojis, also you can use demoji library) Your code should work for any text input



  ```
      **Sample Input Text:**
      # My heart swells with happiness as I bask in the warmth of your presence, grateful for every moment shared together. Yet, a twinge of sadness tugs at my soul. Despite the challenges, I'm excited for the future, determined to overcome any obstacles that come our way.


      **Output Example:**
      My ❤️ swells with happiness as I bask in the warmth of your presence, grateful for every moment shared together. Yet, a twinge of 😞 tugs at my soul. Despite the challenges, I'm 😃 for the future, determined to overcome any obstacles that come our way.
  ```

In [7]:
def convert_to_emojis(text):
    emoji_map = {
        "happy": "😊",
        "happiness": "😊",
        "sad": "😢",
        "sadness": "😞",
        "love": "❤️",
        "heart": "❤️",
        "excited": "😃",
        "angry": "😡",
        "angrily": "😠",
        "fear": "😨",
        "scared": "😱",
        "crying": "😭",
        "surprised": "😲",
        "grateful": "🙏",
        "determined": "💪",
        "laughing": "😂",
        "joy": "😁",
        "confused": "😕",
        "bored": "😐",
        "tired": "😴",
        "sick": "🤒",
        "cool": "😎",
        "kiss": "😘",
        "wink": "😉",
        "angry": "😠",
        "nervous": "😬",
        "blessed": "😇"
    }

    words = text.split()
    new_words = []
    for word in words:
        key = word.lower().strip(".,!?")  # Normalize word
        if key in emoji_map:
            # Replace while preserving punctuation
            emoji = emoji_map[key]
            punct = ''.join(c for c in word if not c.isalnum())
            new_words.append(emoji + punct)
        else:
            new_words.append(word)
    return ' '.join(new_words)

# Sample Input
input_text = ("My heart swells with happiness as I bask in the warmth of your presence, "
              "grateful for every moment shared together. Yet, a twinge of sadness tugs at my soul. "
              "Despite the challenges, I'm excited for the future, determined to overcome any obstacles that come our way.")

# Output
output_text = convert_to_emojis(input_text)
print(output_text)

My ❤️ swells with 😊 as I bask in the warmth of your presence, 🙏 for every moment shared together. Yet, a twinge of 😞 tugs at my soul. Despite the challenges, I'm 😃 for the future, 💪 to overcome any obstacles that come our way.

## Task 2 - Book Dataset (1 point)

Using, Python and various libraries read the .txt files containing the books, the ratings, and the user data that you can find at the [urls](https://github.com/Majid-Sohrabi/2025_Python_Cognitive/tree/main/Datasets) defined below.

1. Concatenate all three files into a single .txt file (Your task is to combine the information from three separate text files into a single cohesive dataset).
The resulting dataset should contain all relevant information from each file, merged together appropriately. save the newly generated file as ***YOURNAME_BOOKS_DATA.txt***. (use comma seprated value)

2. Find out which book has the highest number of reviews and which has lowest number of reviews? (just print it in your code cell).

3. Find out which book has the highest average rating - but include only books that have at least 100 reviews!

4. From the YOURNAME_BOOKS_DATA.txt generate a list of all the countries present in the dataset. Then, find the highest rated book in each one of those countries. (Each book/Country) and simply print it


Full Datasets available on this: [Dataset URL](https://github.com/Majid-Sohrabi/2025_Python_Cognitive/tree/main/Datasets) or you can use below code cell to call dataset

1.   **users.txt**: Contains information about users, including their *user ID, age, and country*.
2.   **ratings.txt**: Contains information about book ratings given by users, including the *user ID, ISBN of the book, and the rating* given.
3.   **books.txt**: Contains information about books, including the *ISBN, title, and author*.

In [2]:
users_url = "https://github.com/Majid-Sohrabi/2025_Python_Cognitive/blob/main/Datasets/users.txt"
ratings_url = "https://github.com/Majid-Sohrabi/2025_Python_Cognitive/blob/main/Datasets/ratings.txt"
books_url = "https://github.com/Majid-Sohrabi/2025_Python_Cognitive/blob/main/Datasets/books.txt"

### 1: Concatenate all three files into a single .txt file

In [10]:
import pandas as pd

users_df = pd.read_csv("datasets/users.txt")
ratings_df = pd.read_csv("datasets/ratings.txt")
books_df = pd.read_csv("datasets/books.txt")

user_rat_df = pd.merge(users_df,ratings_df, how='outer', on="user_id")
df = pd.merge(user_rat_df,books_df, how='outer', on="ISBN")

df

,user_id,age,country,ISBN,rating,title,author
0,NaN,NaN,NaN,0001046438,NaN,Liar,Stephen Fry
1,NaN,NaN,NaN,0001046713,NaN,Twopence to Cross the Mersey,Helen Forrester
2,NaN,NaN,NaN,000104687X,NaN,"T.S. Eliot Reading \The Wasteland\"" and Other ...",T.S. Eliot
3,NaN,NaN,NaN,0001047213,NaN,The Fighting Man,Gerald Seymour
4,NaN,NaN,NaN,0001047973,NaN,Brave New World,Aldous Huxley
...,...,...,...,...,...,...,...
378726,278838.0,15.0,usa,NaN,NaN,NaN,NaN
378727,278840.0,45.0,usa,NaN,NaN,NaN,NaN
378728,278852.0,32.0,australia,NaN,NaN,NaN,NaN
378729,278853.0,17.0,united kingdom,NaN,NaN,NaN,NaN
378730,278855.0,50.0,united kingdom,NaN,NaN,NaN,NaN

In [11]:
df.to_csv('OKORE_VICTORY_CHIDINMA_BOOKS_DATA.txt')

### 2: Book with the highest and lowest number of reviews

In [12]:
review_counts = df['title'].value_counts()
most_reviewed = review_counts.idxmax()
least_reviewed = review_counts.idxmin()
print("Book with the highest number of reviews:", most_reviewed)
print("Book with the lowest number of reviews:", least_reviewed)

Book with the highest number of reviews: Wild Animus
Book with the lowest number of reviews: Chicago Loop

### 3: Find out which book has the highest average rating - but include only books that have at least 100 reviews!

In [18]:
rating_stats = df.groupby('title').agg({'rating': ['mean', 'count']})
rating_stats.columns = ['average_rating', 'review_count']
qualified_books = rating_stats[rating_stats['review_count'] >= 100]
top_rated_book = qualified_books['average_rating'].idxmax()
print("\nHighest average rated book (min 100 reviews):", top_rated_book)

Highest average rated book (min 100 reviews): Harry Potter and the Goblet of Fire (Book 4)

### 4: Highest rated book per country

In [16]:
country_rating_stats = df.groupby(['country', 'title']).agg({'rating': 'mean'}).reset_index()

top_books_by_country = country_rating_stats.loc[country_rating_stats.groupby('country')['rating'].idxmax()]
print("\nHighest rated book in each country:")
pd.DataFrame(top_books_by_country)

Highest rated book in each country:

,country,title,rating
2,argentina,Cyrano De Bergerac (Bantam Classics),10.0
16,australia,1984,10.0
1311,austria,1984,10.0
1560,belgium,Almost Adam,10.0
1692,brazil,1984,10.0
1906,canada,9-11,10.0
7214,chile,Dharma Bums,10.0
7234,china,A Wind in the Door,10.0
7386,croatia,Chocolat,9.0
7393,denmark,Animal Farm,10.0
7450,finland,A Time to Kill,10.0
7605,france,52 Deck Series: 52 Ways to Celebrate Friendship,10.0
8093,germany,52 Deck Series: 52 Ways to Celebrate Friendship,10.0
9239,greece,Bel Canto: A Novel,10.0
9251,india,From the Mixed-Up Files of Mrs. Basil E. Frank...,10.0
9274,indonesia,Notes From a Small Planet,9.0
9281,iran,A Perfect Stranger,10.0
9432,ireland,A Little Princess,10.0
9546,israel,American Psycho (Vintage Contemporaries),9.0
9600,italy,Beyond The Far Side,10.0
9794,japan,A Brief History of Time : From the Big Bang to...,10.0
9911,malaysia,1st to Die: A Novel,10.0
10564,mexico,El Codigo Da Vinci / The Da Vinci Code,10.0
10616,netherlands,A History of the World in 10 1/2 Chapters (Vin...,10.0
11115,new zealand,A Heartbreaking Work of Staggering Genius,10.0
11357,nigeria,Seven Habits Of Highly Effective People,10.0
11362,norway,A Lesson Before Dying (Vintage Contemporaries ...,10.0
11493,pakistan,The Secret Life of Bees,7.0
11497,philippines,A Fire Upon The Deep (Zones of Thought),10.0
11659,poland,A Woman of No Importance (Penguin Popular Clas...,10.0
11732,portugal,1984 (Everyman's Library),10.0
12643,romania,Angels &amp; Demons,10.0
12776,singapore,52 Deck Series: 52 Ways to Celebrate Friendship,10.0
12958,slovakia,Selected Tales (Penguin Popular Classics),10.0
12959,south africa,A Walk to Remember,10.0
12979,south korea,A Bend in the Road,10.0
13006,spain,52 Deck Series: 52 Ways to Celebrate Friendship,10.0
13857,sweden,Dracula (Wordsworth Classics),10.0
13936,switzerland,Angela's Ashes: A Memoir,10.0
14283,turkey,The Catcher in the Rye,10.0
14297,united kingdom,2001 Cross-Stitch Designs: The Essential Refer...,10.0
16235,usa,2001 Cross-Stitch Designs: The Essential Refer...,10.0

## Task 3 - Automating University Admission Process (1.5 point)

Develop a Python program using OOP to automate the admission process for a university based on the marks scored in a qualifying exam. Each student is represented by a unique student ID, along with their age and marks obtained in the exam.

**Data Validity Criteria:**

1. **Age:** The age of the student must be greater than 17 years.
2. **Marks:** The marks obtained by the student must be within the range of 0 to 100 (both inclusive).

**Admission Qualification Criteria:**

A student qualifies for admission if the following conditions are met:

1. The age and marks of the student are valid according to the criteria mentioned above.
2. The marks obtained by the student are 35 or more.

**Scholarship Calculation:**

Based on the marks obtained by the student, the following scholarship percentages are applicable:

*   96-100: 100% Scholarship
*   86-95: 75% Scholarship
*   76-85: 50% Scholarship
*   60-75: 20% Scholarship
*   50-60: 10% Scholarship
*   Below 50: No scholarship; full tuition fees apply.


Write a python program to represent the students seeking admission in the university with atleast 5 students input test

In [5]:
class Student:
    def __init__(self, student_id, age, marks):
        self.student_id = student_id
        self.age = age
        self.marks = marks
        self.is_qualified = False
        self.scholarship_percentage = 0
        self.reason = ""
        self.check_qualification()

    def validate_age(self):
        return self.age > 17

    def validate_marks(self):
        return 0 <= self.marks <= 100

    def check_qualification(self):
        if not self.validate_age():
            self.reason = "Age must be greater than 17"
            return
        if not self.validate_marks():
            self.reason = "Marks must be between 0 and 100"
            return
        if self.marks < 35:
            self.reason = "Marks less than 35"
            return
        self.is_qualified = True
        self.set_scholarship()

    def set_scholarship(self):
        if self.marks >= 96:
            self.scholarship_percentage = 100
        elif self.marks >= 86:
            self.scholarship_percentage = 75
        elif self.marks >= 76:
            self.scholarship_percentage = 50
        elif self.marks >= 60:
            self.scholarship_percentage = 20
        elif self.marks >= 50:
            self.scholarship_percentage = 10
        else:
            self.scholarship_percentage = 0

    def display_student(self):
        print(f"Student ID: {self.student_id}")
        print(f"Age: {self.age}")
        print(f"Marks: {self.marks}")
        if self.is_qualified:
            print("Qualified for Admission: Yes")
            print(f"Scholarship Percentage: {self.scholarship_percentage}%")
        else:
            print("Qualified for Admission: No")
            print(f"Reason: {self.reason}")
        print()


students = [
    Student(1, 18, 97),
    Student(2, 18, 90),
    Student(3, 17, 90),
    Student(4, 18, 101),
    Student(5, 18, 30),
    Student(6, 19, 85),
    Student(7, 20, 65),
    Student(8, 18, 55),
    Student(9, 19, 45)
]

for student in students:
    student.display_student()

Student ID: 1
Age: 18
Marks: 97
Qualified for Admission: Yes
Scholarship Percentage: 100%

Student ID: 2
Age: 18
Marks: 90
Qualified for Admission: Yes
Scholarship Percentage: 75%

Student ID: 3
Age: 17
Marks: 90
Qualified for Admission: No
Reason: Age must be greater than 17

Student ID: 4
Age: 18
Marks: 101
Qualified for Admission: No
Reason: Marks must be between 0 and 100

Student ID: 5
Age: 18
Marks: 30
Qualified for Admission: No
Reason: Marks less than 35

Student ID: 6
Age: 19
Marks: 85
Qualified for Admission: Yes
Scholarship Percentage: 50%

Student ID: 7
Age: 20
Marks: 65
Qualified for Admission: Yes
Scholarship Percentage: 20%

Student ID: 8
Age: 18
Marks: 55
Qualified for Admission: Yes
Scholarship Percentage: 10%

Student ID: 9
Age: 19
Marks: 45
Qualified for Admission: Yes
Scholarship Percentage: 0%

## Task 4 - TollBooth (1.5 point)

Imagine a tollbooth at a bridge. Vehicle passing by the booth are expected to pay or freely pass with a toll fee based on their vehicle type:


*   **Bikes, Two-Wheeler and Scooter** pass for **free** (pay no toll).
*   **Cars** are charged **500 rubles**.
*   **Trucks/Buses** are charged **1200 rubles**.
*   **Heavy-duty equipment vehicles** are charged **1500 rubles**.


The tollbooth keeps track of the number of vehicles that have passed and the total amount of money collected.

Model this tollbooth with a class called ***TollBooth***. The two data items are an unsigned integer to hold the total number of vehicles and an integer to hold the total amount of money collected. A constructor initializes both of these to zero.

Implement the following member functions:

1. **payVehicle(int toll)**: Increments the vehicle total and adds the specified toll amount to the cash total.
2. **noPayVehicle()**: Increments the vehicle total but adds nothing to the cash total.
3. **display()**: Displays the total number of vehicles and the total amount of money collected.

Create an object of this class in the main function. Continuously display a menu to the user, allowing them to choose the type of vehicle passing by. Update the tollbooth accordingly and display the total statistics. Keep displaying the menu until the user chooses to exit the program.

In [11]:
class TollBooth:
    def __init__(self):
        self.total_vehicles = 0
        self.total_cash = 0

    def payVehicle(self, toll):
        self.total_vehicles += 1
        self.total_cash += toll

    def noPayVehicle(self):
        self.total_vehicles += 1

    def display(self):
        print(f"Total Vehicles: {self.total_vehicles}")
        print(f"Total Cash Collected: {self.total_cash} rubles")

tollbooth = TollBooth()
while True:
    print("\nTollBooth Menu:")
    print("1. Bike/Two-Wheeler/Scooter (Free)")
    print("2. Car (500 rubles)")
    print("3. Truck/Bus (1200 rubles)")
    print("4. Heavy-duty equipment (1500 rubles)")
    print("5. Exit")
    choice = input("Enter choice (1-5): ")
    
    if choice == '1':
        tollbooth.noPayVehicle()
        tollbooth.display()
    elif choice == '2':
        tollbooth.payVehicle(500)
        tollbooth.display()
    elif choice == '3':
        tollbooth.payVehicle(1200)
        tollbooth.display()
    elif choice == '4':
        tollbooth.payVehicle(1500)
        tollbooth.display()
    elif choice == '5':
        print("Final Statistics:")
        tollbooth.display()
        break
    else:
        print("Invalid choice, please try again.")

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  1

Total Vehicles: 1
Total Cash Collected: 0 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  1

Total Vehicles: 2
Total Cash Collected: 0 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  1

Total Vehicles: 3
Total Cash Collected: 0 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  1

Total Vehicles: 4
Total Cash Collected: 0 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  1

Total Vehicles: 5
Total Cash Collected: 0 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  1

Total Vehicles: 6
Total Cash Collected: 0 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  3

Total Vehicles: 7
Total Cash Collected: 1200 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  4

Total Vehicles: 8
Total Cash Collected: 2700 rubles

TollBooth Menu:
1. Bike/Two-Wheeler/Scooter (Free)
2. Car (500 rubles)
3. Truck/Bus (1200 rubles)
4. Heavy-duty equipment (1500 rubles)
5. Exit

Enter choice (1-5):  5

Final Statistics:
Total Vehicles: 8
Total Cash Collected: 2700 rubles

## Task 5 - Coding Challenge Practice (1 point)

**Challenge 1:** Below is a list of Famous personalities in the world.

In [19]:
presidents_full = ["Michael Jackson", "Nelson Mandela", "Albert Einstein", "Mahatma Gandhi", "Yuri Gagarin", \
        "Marilyn Monroe", "Anne Frank", "Thomas Alva Edison", "Narendra Modi", "Neil Armstrong", \
        "J.K.Rowling", "Leo Tolstoy", "Henry Ford", "Pablo Picasso", "Steve Jobs", \
        "Abraham Lincoln", "Cristiano Ronaldo", "Magnus Carlsen", "Alexander Pushkin", "Donald Trump", \
        "Charlie Chaplin", "Leonardo Da Vinci", "Leonardo DiCaprio", "Jackie Chan", "Stephen Hawking", \
        "Osho Rajneesh", "John Cena", "Bernard Arnault", "Mark Twain", "Usain Bolt", \
        "Bruce Lee", "Jalāl al-Dīn Muḥammad Rumi", "Alex Ovechkin", "Elon Musk", "John F. Kennedy", \
        "James Stephen", "Richard Branson", "Michael Phelps", "Jeff Bezos", "Ken Jeong", "Swami Vivekananda", \
        "Bill Clinton", "Daniil Medvedev", "Mother Teresa"]

Create a new list that contains only the last name of each person.

In [20]:
for name in presidents_full:
    print(name.strip().split()[-1])

Jackson
Mandela
Einstein
Gandhi
Gagarin
Monroe
Frank
Edison
Modi
Armstrong
J.K.Rowling
Tolstoy
Ford
Picasso
Jobs
Lincoln
Ronaldo
Carlsen
Pushkin
Trump
Chaplin
Vinci
DiCaprio
Chan
Hawking
Rajneesh
Cena
Arnault
Twain
Bolt
Lee
Rumi
Ovechkin
Musk
Kennedy
Stephen
Branson
Phelps
Bezos
Jeong
Vivekananda
Clinton
Medvedev
Teresa

Create a list of all the personalities whose First name starts with the letter M.

In [21]:
output = []
for name in presidents_full:
    first_name = name.strip().split()[0]
    if first_name[0] == 'M':
        output.append(name)

print(output)

['Michael Jackson', 'Mahatma Gandhi', 'Marilyn Monroe', 'Magnus Carlsen', 'Mark Twain', 'Michael Phelps', 'Mother Teresa']

**Challenge 2:** Fill in the blanks in each of the programs below to produce the indicated result.

In [22]:
# Total length of the strings in the list: ["red", "green", "blue"] => 12
total = 0
for word in ["red", "green", "blue"]:
    total = total + len(word)
print(total)

12

In [24]:
# List of word lengths: ["red", "green", "blue"] => [3, 5, 4]
lengths = []
for word in ["red", "green", "blue"]:
    lengths.append(len(word))
print(lengths)

[3, 5, 4]

In [25]:
# Concatenate all words: ["red", "green", "blue"] => "redgreenblue"
words = ["red", "green", "blue"]
result = ''
for word in words:
    result += word
print(result)

redgreenblue